context:
  version: "3.1.0"
  build_number: 2

package:
  name: xeus-zmq
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-zmq/archive/${{ version }}.tar.gz
  sha256: 55ebfca641e2295dbc0d6c85dbfb54810762bc0792d3e464d32f79a5ce0bdd26

build:
  number: ${{ build_number }}

requirements:
  run_exports:
    - ${{ pin_subpackage('xeus-zmq', upper_bound='x.x') }}
  build:
    - cmake
    - ninja
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - if: unix
      then:
        - pkg-config
  host:
    - nlohmann_json
    - nlohmann_json-abi
    - cppzmq >=4.8.1,<5
    - zeromq
    - openssl <4.0
    - xeus >=5,<6.0
    - if: linux
      then:
        - libuuid
  # zeromq, libuuid and xeus have run_exports sections. No need to add them as
  # run requirements. xeus headers expose headers from nlohmann_json 
  # but does not depend on them at runtime.
  run_constraints:
    - ${{ pin_compatible('cppzmq', upper_bound='x.x') }}

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}include/xeus-zmq/xeus-zmq.hpp
          - ${{ "Library/" if win }}lib/cmake/xeus-zmq/xeus-zmqConfig.cmake
          - ${{ "Library/" if win }}lib/cmake/xeus-zmq/xeus-zmqConfigVersion.cmake

about:
  homepage: https://github.com/jupyter-xeus/xeus-zmq
  repository: https://github.com/jupyter-xeus/xeus-zmq
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ZeroMQ-based middleware for xeus
  description: ZeroMQ-based middleware for xeus
  documentation: https://xeus.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - anutosh491
